package com.ekalife.utils;

import id.co.sinarmaslife.std.model.vo.DropDown;

import java.util.ArrayList;
import java.util.List;

public class Telpon {

	public static List<DropDown> daftarExtension(){
		List<DropDown> result = new ArrayList<DropDown>();
		result.add(new DropDown("Accounting", "8200", "JULINA HASAN*"));
		result.add(new DropDown("Accounting", "5606", "HIRAMAN HATI FA"));
		result.add(new DropDown("Accounting", "8216", "AGNES TEDJA"));
		result.add(new DropDown("Accounting", "8216", "SUGIARTO"));
		result.add(new DropDown("Accounting", "8216", "TONY"));
		result.add(new DropDown("Accounting", "8217", "ASKA APRIANI"));
		result.add(new DropDown("Accounting", "8217", "HERIANTO"));
		result.add(new DropDown("Accounting", "8217", "TRI LESTARI"));
		result.add(new DropDown("Accounting", "8319", "MARIO NELSON"));
		result.add(new DropDown("Accounting", "8320", "ARNOLD"));
		result.add(new DropDown("Accounting", "8320", "ARNOLD"));
		result.add(new DropDown("Accounting", "8320", "SARTIKA RATNA"));
		result.add(new DropDown("Actuarial & Reinsurance", "8701", "HERMAN SULISTYO*"));
		result.add(new DropDown("Actuarial & Reinsurance", "8366", "DIAN PERMATA SARI"));
		result.add(new DropDown("Actuarial & Reinsurance", "8560", "ACHMAD ANWARUDIN"));
		result.add(new DropDown("Actuarial & Reinsurance", "5959", "NENI FERINA"));
		result.add(new DropDown("Actuarial & Reinsurance", "8539", "FITRIYANA MAYA D."));
		result.add(new DropDown("Actuarial & Reinsurance", "8708", "JOELONG"));
		result.add(new DropDown("Actuarial & Reinsurance", "8902", "PUTU JAYA"));
		result.add(new DropDown("Actuarial & Reinsurance", "8902", "KAMAPUTTA"));
		result.add(new DropDown("Actuarial & Reinsurance", "8941", "DWI KUSUMA"));
		result.add(new DropDown("Actuarial & Reinsurance", "8941", "YUDHA WIJAYA"));
		result.add(new DropDown("Actuarial & Reinsurance", "8942", "DESVINNA HIDAWATI"));
		result.add(new DropDown("Actuarial & Reinsurance", "8943", "SUGIARTO"));
		result.add(new DropDown("Actuarial & Reinsurance", "8944", "RIDO AFMAJA S."));
		result.add(new DropDown("Actuarial & Reinsurance", "8945", "FERVENTIKA SUNDAH"));
		result.add(new DropDown("Actuarial & Reinsurance", "8946", "DAVID HUSAINI"));
		result.add(new DropDown("Agency Division/Training", "8306", "JOS CHANDRA I.*"));
		result.add(new DropDown("Agency Division/Training", "8305", "WINATA SUHARDI"));
		result.add(new DropDown("Agency Division/Training", "8344", "INDRIA HERAWATI"));
		result.add(new DropDown("Agency Division/Training", "8386", "EUFRAT"));
		result.add(new DropDown("Agency Division/Training", "8534", "ANTHONIUS HERMAN T."));
		result.add(new DropDown("Agency Division/Training", "8303", "RD. BAMBANG T. P."));
		result.add(new DropDown("Audit", "8219", "EDI SARTANA*"));
		result.add(new DropDown("Audit", "8348", "INDRA SYAILENDRA"));
		result.add(new DropDown("Audit", "8948", "AMELIA"));
		result.add(new DropDown("Audit", "8948", "HENDRA "));
		result.add(new DropDown("Admin Lantai 9 (Kantor Pusat)", "5229", "YUSSI*"));
		result.add(new DropDown("Admin Lantai 9 (Kantor Pusat)", "5914", "REDY"));
		result.add(new DropDown("Admin Lantai 9 (Kantor Pusat)", "5401", "IWAN SURYA"));
		result.add(new DropDown("Admin Lantai 9 (Kantor Pusat)", "5200", "KRISNA"));
		result.add(new DropDown("Bancassurance 2", "5607", "DWI PANGESTUTI*"));
		result.add(new DropDown("Bancassurance 2", "8572", "SHILTA SHAVISTA"));
		result.add(new DropDown("Bancassurance 2", "8572", "USMAYANTI"));
		result.add(new DropDown("Biro Direksi", "8881", "MAUREEN MOUDY"));
		result.add(new DropDown("Biro Direksi", "8882", "YOSEFINA"));
		result.add(new DropDown("Branch Admin Support", "8103", "LIM ARIEF*"));
		result.add(new DropDown("Branch Admin Support", "8102", "HENDRA"));
		result.add(new DropDown("Branch Admin Support", "8102", "JUNE GLORY"));
		result.add(new DropDown("Branch Admin Support", "8401", "DESY EKA"));
		result.add(new DropDown("Branch Admin Support", "8401", "RUDIANTO"));
		result.add(new DropDown("Branch Admin Support", "8401", "HUSNUL HULUK"));
		result.add(new DropDown("Branch Admin Support", "8401", "MARTINO"));
		result.add(new DropDown("Branch Admin Support", "8379", "IVANA"));
		result.add(new DropDown("Branch Admin Support", "8379", "MARTIN HADI"));
		result.add(new DropDown("Branch Admin Support", "8379", "KEKE"));
		result.add(new DropDown("Branch Admin Support", "8379", "BEBI"));
		result.add(new DropDown("Branch Admin Support", "8381", "ALFIN ANDI"));
		result.add(new DropDown("Branch Admin Support", "8381", "ROHMAT"));
		result.add(new DropDown("Branch Admin Support", "8381", "YUSUP"));
		result.add(new DropDown("Branch Admin Support", "8954", "FABRY FAHLEVI"));
		result.add(new DropDown("Business Development", "8525", "ANI CHRISWANTINI*"));
		result.add(new DropDown("Business Development", "8308", "MARIA DEWI FEBRIANTI "));
		result.add(new DropDown("Business Development", "5824", "ANGGI YANTI"));
		result.add(new DropDown("Business Development", "5703", "AYU GUSTIRAMADHANI"));
		result.add(new DropDown("Business Development", "5917", "FEBRINA INDAHWATI"));
		result.add(new DropDown("Business Development", "5702", "SITI LASYAH ALMAKAWI "));
		result.add(new DropDown("Business Development", "5627", "SITI PARNIATUN"));
		result.add(new DropDown("Business Development", "8387", "VRITA RIA YOLANDA"));
		result.add(new DropDown("Claims", "8346", "SISTI KARSINAH*"));
		result.add(new DropDown("Claims", "8713", "SUNARTI"));
		result.add(new DropDown("Claims", "5818", "RENY"));
		result.add(new DropDown("Claims", "5818", "DARISMA"));
		result.add(new DropDown("Claims", "5818", "MIFTAH"));
		result.add(new DropDown("Claims", "8345", "NURAFNI"));
		result.add(new DropDown("Claims", "8345", "KIKI"));
		result.add(new DropDown("Claims", "8703", "KARTIKA NURAINI"));
		result.add(new DropDown("Claims", "8806", "BERNADUS DECKY M."));
		result.add(new DropDown("Corporate Marketing", "8953", "ADE MAULANA*"));
		result.add(new DropDown("Corporate Marketing", "8953", "AHMAD FARHAN"));
		result.add(new DropDown("Corporate Marketing", "8953", "ARIF BUSTANUL ARIFIN "));
		result.add(new DropDown("Corporate Marketing", "8953", "ARIS BUDI PRIHMANTYO "));
		result.add(new DropDown("Corporate Marketing", "8953", "SYAMSU REVAI"));
		result.add(new DropDown("Corporate Marketing", "8953", "YULKARNAINI"));
		result.add(new DropDown("Corporate Underwriting", "5812", "RIKA RACHEL P.*"));
		result.add(new DropDown("Corporate Underwriting", "8301", "EKA PUTRI"));
		result.add(new DropDown("Corporate Underwriting", "8301", "LAYLA"));
		result.add(new DropDown("Corporate Underwriting", "8358", "KUSMIATI"));
		result.add(new DropDown("Corporate Underwriting", "8368", "JUDIKA MARIANA"));
		result.add(new DropDown("Corporate Underwriting", "8526", "NANA"));
		result.add(new DropDown("Corporate Underwriting", "8526", "DIDIK"));
		result.add(new DropDown("Corporate Underwriting", "8526", "DONNY"));
		result.add(new DropDown("Corporate Underwriting", "8527", "ADE WIDAYURENI"));
		result.add(new DropDown("Corporate Underwriting", "8527", "SOFYAN"));
		result.add(new DropDown("Corporate Underwriting", "8528", "NINGRUM"));
		result.add(new DropDown("Corporate Underwriting", "8528", "ILA"));
		result.add(new DropDown("Corporate Underwriting", "8568", "EU FUNG LANG"));
		result.add(new DropDown("Corporate Underwriting", "8568", "SEPTI"));
		result.add(new DropDown("Corporate Underwriting", "8568", "RIENNE"));
		result.add(new DropDown("Corporate Underwriting", "8568", "ANTON"));
		result.add(new DropDown("Corporate Underwriting", "8767", "ANITA"));
		result.add(new DropDown("Corporate Underwriting", "8767", "MERRY"));
		result.add(new DropDown("Corporate Underwriting", "8767", "STEFANUS"));
		result.add(new DropDown("Customer Service Back Office", "8610", "YULIA ANDRI H. D. P.*"));
		result.add(new DropDown("Customer Service Back Office", "8375", "BONG THERESIA Y. A."));
		result.add(new DropDown("Customer Service Back Office", "5431", "MERLINA"));
		result.add(new DropDown("Customer Service Back Office", "5609", "ETY HERIYANTI"));
		result.add(new DropDown("Customer Service Back Office", "5820", "ERI DWI PRATIWI"));
		result.add(new DropDown("Customer Service Back Office", "5821", "HELENA"));
		result.add(new DropDown("Customer Service Back Office", "5823", "EKO ARIANTO"));
		result.add(new DropDown("Customer Service Back Office", "5830", "MERLINA"));
		result.add(new DropDown("Customer Service Back Office", "5957", "ALI AKBAR"));
		result.add(new DropDown("Customer Service Back Office", "5958", "TAUFIK"));
		result.add(new DropDown("Customer Service Back Office", "5958", "YOFFI"));
		result.add(new DropDown("Customer Service Back Office", "8208", "SRI REDJEKI ANNALYSA"));
		result.add(new DropDown("Customer Service Back Office", "8323", "WAHDAHNIYAH ( NIA )"));
		result.add(new DropDown("Customer Service Back Office", "8324", "IMRAN"));
		result.add(new DropDown("Customer Service Back Office", "8325", "RIKA KURNIASARI"));
		result.add(new DropDown("Customer Service Back Office", "8331", "ADITYA"));
		result.add(new DropDown("Customer Service Back Office", "8331", "WINDA"));
		result.add(new DropDown("Customer Service Back Office", "8408", "DWI BUDIAJI"));
		result.add(new DropDown("Customer Service Back Office", "8408", "HASMAH"));
		result.add(new DropDown("Customer Service Back Office", "8408", "KOMENG"));
		result.add(new DropDown("Customer Service Back Office", "8413", "ADITYA"));
		result.add(new DropDown("Customer Service Back Office", "8542", "AHMAD FADILLAH"));
		result.add(new DropDown("Customer Service Back Office", "8556", "EVI RIYANI"));
		result.add(new DropDown("Customer Service Back Office", "8940", "CHILLA"));
		result.add(new DropDown("Customer Service Back Office", "8940", "SRI KUNCORO"));
		result.add(new DropDown("Customer Service Help Desk", "5319", "IRIANA WIJAYANTI*"));
		result.add(new DropDown("Customer Service Help Desk", "5605", "WENNY P."));
		result.add(new DropDown("Customer Service Help Desk", "5909", "ANITA RAHMAWATI"));
		result.add(new DropDown("Customer Service Help Desk", "8365", "RR.SURYANINGSIH"));
		result.add(new DropDown("Customer Service Help Desk", "8517", "TRI UTAMI HANDAYANI"));
		result.add(new DropDown("Customer Service Help Desk", "8537", "BETA VIANISA"));
		result.add(new DropDown("Customer Service Help Desk", "8567", "FETTY PANCAWATI"));
		result.add(new DropDown("Customer Service Help Desk", "8570", "MURDIASIH WIDIASTUTI"));
		result.add(new DropDown("Customer Service Help Desk", "8579", "PRIHATMOKO"));
		result.add(new DropDown("Customer Service Help Desk", "8704", "ANGGRIATI"));
		result.add(new DropDown("Customer Service Help Desk", "8730", "ANNA WIDIYANTI"));
		result.add(new DropDown("Distribution Support", "8612", "TRI HANDINI*"));
		result.add(new DropDown("Distribution Support", "8506", "JELITA SAMOSIR"));
		result.add(new DropDown("Distribution Support", "8202", "MOLLY WESNI"));
		result.add(new DropDown("Distribution Support", "8613", "WENNY WIDANINGSIH"));
		result.add(new DropDown("Distribution Support", "8326", "EDHY"));
		result.add(new DropDown("Distribution Support", "8326", "ROBBY"));
		result.add(new DropDown("Distribution Support", "8326", "MARTONO"));
		result.add(new DropDown("Distribution Support", "8611", "ALI"));
		result.add(new DropDown("Distribution Support", "8611", "ARIS"));
		result.add(new DropDown("Distribution Support", "8613", "J. TOHOM D. H."));
		result.add(new DropDown("Distribution Support", "8950", "ASIMA"));
		result.add(new DropDown("Distribution Support", "8950", "HISAR"));
		result.add(new DropDown("Dolphin Team", "5932", "EKA PRAYUDI*"));
		result.add(new DropDown("Dolphin Team", "5930", "HANS WIRAWAN"));
		result.add(new DropDown("Dolphin Team", "5930", "SETRO GONDO"));
		result.add(new DropDown("Dolphin Team", "5931", "JOSI"));
		result.add(new DropDown("Dolphin Team", "5931", "ERVAN"));
		result.add(new DropDown("Dolphin Team", "5931", "DANTI"));
		result.add(new DropDown("Finance", "8203", "VONNY TANAJA TAN*"));
		result.add(new DropDown("Finance", "8211", "APRINA ARI P. C."));
		result.add(new DropDown("Finance", "5807", "DEWI RIA"));
		result.add(new DropDown("Finance", "5825", "NITA ARISTA"));
		result.add(new DropDown("Finance", "8207", "AGUS K. L."));
		result.add(new DropDown("Finance", "8209", "MURNIATI"));
		result.add(new DropDown("Finance", "8210", "EDMOND"));
		result.add(new DropDown("Finance", "8210", "HONG LIAN"));
		result.add(new DropDown("Finance", "8210", "LIANA"));
		result.add(new DropDown("Finance", "8210", "DENGGAN"));
		result.add(new DropDown("Finance", "8211", "ELLEN MAGDALENA"));
		result.add(new DropDown("Finance", "8212", "CLARA"));
		result.add(new DropDown("Finance", "8212", "SUHENDRA"));
		result.add(new DropDown("Finance", "8222", "ROSITA HERMAWATI"));
		result.add(new DropDown("Finance", "8317", "SUCI"));
		result.add(new DropDown("Finance", "8318", "WIDYA RIGOSARI"));
		result.add(new DropDown("Finance", "8318", "MARIA RETNO"));
		result.add(new DropDown("Finance", "8321", "EMIRENTIANE"));
		result.add(new DropDown("Finance", "8321", "EKO PRASETYO"));
		result.add(new DropDown("Finance", "8341", "SISCA"));
		result.add(new DropDown("Finance", "8341", "INTAN"));
		result.add(new DropDown("Finance", "8397", "WINARTI"));
		result.add(new DropDown("Finance", "8367", "EVIE SUPRIYATI"));
		result.add(new DropDown("Finance", "8397", "PUJI"));
		result.add(new DropDown("Finance", "8397", "BASISWO"));
		result.add(new DropDown("Finance", "8397", "NGADINO"));
		result.add(new DropDown("Finance", "8511", "ANGO"));
		result.add(new DropDown("Finance", "8558", "ANACE HUWAE"));
		result.add(new DropDown("Finance", "8600", "DESFRINA"));
		result.add(new DropDown("General Affair", "8215", "SANGA MANIUR S.*"));
		result.add(new DropDown("General Affair", "8220", "FERRYANTO"));
		result.add(new DropDown("General Affair", "8389", "SENTOT MUNADI"));
		result.add(new DropDown("General Affair", "8389", "PERMANA FAUZI"));
		result.add(new DropDown("General Affair", "8956", "SIGIT WIHARSO"));
		result.add(new DropDown("General Affair", "8336", "NOVIANSYAH"));
		result.add(new DropDown("General Affair", "8111", "MURDIYANTO"));
		result.add(new DropDown("General Affair", "8111", "SLAMET RIYADI"));
		result.add(new DropDown("General Affair", "5401", "SURIPTO"));
		result.add(new DropDown("General Affair", "5401", "PUJU"));
		result.add(new DropDown("General Affair", "5401", "ADE ROHMAN"));
		result.add(new DropDown("General Affair", "8529", "SUYANA"));
		result.add(new DropDown("General Affair", "8956", "MAHPUL"));
		result.add(new DropDown("General Affair", "8529", "MAKRUF"));
		result.add(new DropDown("General Affair", "8529", "MARVIN"));
		result.add(new DropDown("General Affair", "5815", "AJI"));
		result.add(new DropDown("General Affair", "5815", "HADIANTO"));
		result.add(new DropDown("General Affair", "5815", "HARYADI"));
		result.add(new DropDown("General Affair", "5815", "ICHSAN"));
		result.add(new DropDown("General Affair", "5815", "INDRA"));
		result.add(new DropDown("General Affair", "5815", "KARWIN"));
		result.add(new DropDown("General Affair", "5815", "MADE"));
		result.add(new DropDown("General Affair", "5815", "MADINAH"));
		result.add(new DropDown("General Affair", "5815", "MANGISI"));
		result.add(new DropDown("General Affair", "5815", "FERDI"));
		result.add(new DropDown("General Affair", "5815", "SUYATNO"));
		result.add(new DropDown("General Affair", "5815", "MUNAWIR"));
		result.add(new DropDown("General Affair", "5815", "WAWAN"));
		result.add(new DropDown("General Affair", "5815", "ASEP"));
		result.add(new DropDown("General Affair", "5815", "HARIYADI"));
		result.add(new DropDown("General Affair", "5815", "ABDURRAHIM"));
		result.add(new DropDown("General Affair", "5815", "ZAELANI"));
		result.add(new DropDown("General Affair", "5815", "ADE"));
		result.add(new DropDown("General Affair", "5815", "ZAENI"));
		result.add(new DropDown("General Affair", "5815", "BAYU"));
		result.add(new DropDown("General Affair", "5815", "DEDI"));
		result.add(new DropDown("General Affair", "5815", "NANO"));
		result.add(new DropDown("General Affair", "5815", "HENDRO"));
		result.add(new DropDown("General Affair", "5815", "SAMIKUN"));
		result.add(new DropDown("General Affair", "8000", "RANI DIAN PUSPITA"));
		result.add(new DropDown("General Affair", "0", "SITI MASLIHA"));
		result.add(new DropDown("General Affair", "0", "ICHA"));
		result.add(new DropDown("Information Technology", "8101", "IWEN LENDER*"));
		result.add(new DropDown("Information Technology", "8103", "KUAN LIANG"));
		result.add(new DropDown("Information Technology", "8110", "DITO"));
		result.add(new DropDown("Information Technology", "8110", "VICKY"));
		result.add(new DropDown("Information Technology", "8105", "BONG HIMMIA"));
		result.add(new DropDown("Information Technology", "8105", "RUDY HERMAWAN"));
		result.add(new DropDown("Information Technology", "8107", "ABDUL RAZAK"));
		result.add(new DropDown("Information Technology", "8107", "KUSENO"));
		result.add(new DropDown("Information Technology", "8107", "WENNY"));
		result.add(new DropDown("Information Technology", "8107", "ANDY"));
		result.add(new DropDown("Information Technology", "8107", "FADLY"));
		result.add(new DropDown("Information Technology", "8107", "PENGKY"));
		result.add(new DropDown("Information Technology", "8109", "YUSUF SUTARKO"));
		result.add(new DropDown("Information Technology", "8109", "YUSUP ANDRI"));
		result.add(new DropDown("Information Technology", "8109", "BERTHO"));
		result.add(new DropDown("Information Technology", "8109", "DEDDY"));
		result.add(new DropDown("Information Technology", "8109", "DIAN"));
		result.add(new DropDown("Information Technology", "8109", "SAMUEL"));
		result.add(new DropDown("Information Technology", "8384", "TANWER"));
		result.add(new DropDown("Information Technology", "8384", "FAISAL"));
		result.add(new DropDown("Information Technology", "8384", "ANWAR"));
		result.add(new DropDown("Information Technology", "8384", "SULAIMAN"));
		result.add(new DropDown("Information Technology", "8333", "AGUNG"));
		result.add(new DropDown("Information Technology", "8333", "YULIYANTI"));
		result.add(new DropDown("Information Technology", "8581", "ANTO (FAX)"));
		result.add(new DropDown("Investment", "8213", "SANDY PRAMONO*"));
		result.add(new DropDown("Investment", "8221", "CALVINA"));
		result.add(new DropDown("Investment", "5555", "SARI YULIANA"));
		result.add(new DropDown("KPR & Collection", "8557", "MARLIANA*"));
		result.add(new DropDown("KPR & Collection", "8951", "R.M.HEDHIASTOMO W."));
		result.add(new DropDown("KPR & Collection", "5835", "STEVANI PURWANTI S."));
		result.add(new DropDown("KPR & Collection", "8947", "HARITJE L."));
		result.add(new DropDown("Legal & HRD", "8414", "YULI KUSUMA R.*"));
		result.add(new DropDown("Legal & HRD", "8705", "EDITA RIANTI A."));
		result.add(new DropDown("Legal & HRD", "8706", "LENNY GANI"));
		result.add(new DropDown("Legal & HRD", "8337", "BULAN ELISABETH N."));
		result.add(new DropDown("Legal & HRD", "5817", "PRIMITA"));
		result.add(new DropDown("Legal & HRD", "5817", "NITA"));
		result.add(new DropDown("Marketing Jakarta 1", "5107", "LIESTYAWATI*"));
		result.add(new DropDown("Marketing Jakarta 1", "5107", "WAHYUDI*"));
		result.add(new DropDown("Marketing Jakarta 1", "5433", "LISA"));
		result.add(new DropDown("Marketing Jakarta 1", "5433", "MUTHIA"));
		result.add(new DropDown("Marketing Jakarta 1", "5433", "IRWAN"));
		result.add(new DropDown("Marketing Jakarta 1", "5700", "LUSI"));
		result.add(new DropDown("Marketing Jakarta 1", "5700", "LENA"));
		result.add(new DropDown("Marketing Jakarta 1", "5700", "MARGARETHA"));
		result.add(new DropDown("Marketing Jakarta 1", "5700", "MARICHE"));
		result.add(new DropDown("Marketing Jakarta 2", "5200", "EVIYANTI*"));
		result.add(new DropDown("Marketing Jakarta 2", "5200", "KRISNA NUNUNG"));
		result.add(new DropDown("Marketing Jakarta 2", "5200", "NOVITA"));
		result.add(new DropDown("Marketing Jakarta 2", "5200", "MAUREEN"));
		result.add(new DropDown("Marketing Jakarta 2", "5200", "D. WIDYASTUTI"));
		result.add(new DropDown("Marketing Jakarta 4", "5400", "VINCA*"));
		result.add(new DropDown("Marketing Jakarta 4", "5424", "ERNI"));
		result.add(new DropDown("Marketing Jakarta 4", "5407", "FIDA"));
		result.add(new DropDown("Marketing Jakarta 4", "5414", "ANDI"));
		result.add(new DropDown("Marketing Jakarta 5", "5917", "SURATNO"));
		result.add(new DropDown("Marketing Jakarta 5", "5927", "DEWI RATNA CANDRA"));
		result.add(new DropDown("Marketing Jakarta 5", "5425", "RIKA"));
		result.add(new DropDown("Marketing Jakarta 5", "5428", "HUSEIN"));
		result.add(new DropDown("Marketing Jakarta 5", "5427", "SUHARNO"));
		result.add(new DropDown("Marketing Jakarta 5", "5114", "DEDEH"));
		result.add(new DropDown("Marketing Jakarta 5", "5620", "DARYONO"));
		result.add(new DropDown("Marketing Jakarta 5", "5412", "-"));
		result.add(new DropDown("Marketing Jakarta 5", "5418", "-"));
		result.add(new DropDown("Marketing Jakarta 9", "5900", "SANTI*"));
		result.add(new DropDown("Marketing Support & Purchasing", "8515", "RENTANIA ROTUA D. S.*"));
		result.add(new DropDown("Marketing Support & Purchasing", "8206", "NOVIANTO ALWIN A."));
		result.add(new DropDown("Marketing Support & Purchasing", "8108", "CANDRA SUARDY"));
		result.add(new DropDown("Marketing Support & Purchasing", "5827", "SAPHRY MARGARETH L."));
		result.add(new DropDown("Marketing Support & Purchasing", "8569", "TRINA DIANY"));
		result.add(new DropDown("Marketing Support & Purchasing", "8513", "OLOI SISCA"));
		result.add(new DropDown("Marketing Support & Purchasing", "8513", "RIKY DANIEL"));
		result.add(new DropDown("Marketing Support & Purchasing", "8543", "TIURMA HERAWATI"));
		result.add(new DropDown("Marketing Support & Purchasing", "8218", "FEBI PRABIMANA"));
		result.add(new DropDown("Marketing Support & Purchasing", "8218", "LIMBAR PARDEN P."));
		result.add(new DropDown("OB & Security Lt 9", "5401", "PUJO"));
		result.add(new DropDown("OB & Security Lt 9", "5401", "ADE R"));
		result.add(new DropDown("OB & Security Lt 9", "5401", "ITO"));
		result.add(new DropDown("Payroll", "8205", "LILY HARTINI*"));
		result.add(new DropDown("Provider Support", "8480", "HAFRIANSYAR*"));
		result.add(new DropDown("Provider Support", "8608", "NETTY SELANNO*"));
		result.add(new DropDown("Provider Support", "5729", "ALDA ASTERIA S."));
		result.add(new DropDown("Provider Support", "8937", "ANDRI NOVIANTO"));
		//result.add(new DropDown("Provider Support", "8360", "ARENAH")); //KARYAWAN RESIGN
		result.add(new DropDown("Provider Support", "8716", "ESTERLINA"));
		result.add(new DropDown("Provider Support", "8563", "I GUSTI BAGUS ARYA"));
		result.add(new DropDown("Provider Support", "8328", "IRMA ROTUA T."));
		result.add(new DropDown("Provider Support", "8322", "IRMA YULISTIA"));
		result.add(new DropDown("Provider Support", "5921", "NISA ISTIQOMAH"));
		result.add(new DropDown("Provider Support", "8369", "RETNANINGSIH"));
		result.add(new DropDown("Provider Support", "8348", "SEPTY CAHYA N."));
		result.add(new DropDown("Provider Support", "5833", "SUPIANTO ZAENAL"));
		result.add(new DropDown("Provider Support", "5513", "SYAMSUL ALAM"));
		result.add(new DropDown("Provider Support", "8707", "SYLVIA SISCA S."));
		result.add(new DropDown("Provider Support", "8329", "WIWIE ZAMZANI"));
		result.add(new DropDown("Provider Support", "8371", "ZUL AKBAR"));
		result.add(new DropDown("Recruitment & Training", "8899", "MEIDY TUMEWU"));
		result.add(new DropDown("Recruitment & Training", "8631", "TOAR BUDHY M."));
		result.add(new DropDown("Recruitment & Training", "5925", "ANDREAS S."));
		result.add(new DropDown("Recruitment & Training", "5931", "CHRISTIANA YUDANTI"));
		result.add(new DropDown("Recruitment & Training", "5925", "JUNITA ISABELLA"));
		result.add(new DropDown("Recruitment & Training", "8214", "HENDRA SANTOSO"));
		result.add(new DropDown("Recruitment & Training", "8332", "SELVI TIOMERLINA"));
		result.add(new DropDown("Recruitment & Training", "8336", "CINDY EVIE"));
		result.add(new DropDown("Recruitment & Training", "8336", "RATIH"));
		result.add(new DropDown("Underwriting Individu", "8618", "INGRID TRISNAWATI K."));
		result.add(new DropDown("Underwriting Individu", "5402", "INGE"));
		result.add(new DropDown("Underwriting Individu", "5402", "APRIYANI"));
		result.add(new DropDown("Underwriting Individu", "8710", "ATIN"));
		result.add(new DropDown("Underwriting Individu", "5606", "DEWI ANDRIYATI"));
		result.add(new DropDown("Underwriting Individu", "5826", "TIMMY"));
		result.add(new DropDown("Underwriting Individu", "5826", "ERY"));
		result.add(new DropDown("Underwriting Individu", "8392", "PAMPILIA DEWI"));
		result.add(new DropDown("Underwriting Individu", "8392", "HENDRA"));
		result.add(new DropDown("Underwriting Individu", "8392", "IVAN"));
		result.add(new DropDown("Underwriting Individu", "8700", "DINNI"));
		result.add(new DropDown("Underwriting Individu", "8700", "RESTA"));
		result.add(new DropDown("Underwriting Individu", "8700", "HANIFAH"));
		result.add(new DropDown("Underwriting Individu", "8711", "ARIN"));
		result.add(new DropDown("Underwriting Individu", "8711", "NOVI"));
		result.add(new DropDown("Underwriting Individu", "8711", "SARI SUTINI"));
		result.add(new DropDown("Underwriting Individu", "8711", "SHOPIAH"));
		result.add(new DropDown("Underwriting Individu", "8711", "TITIS"));
		result.add(new DropDown("Underwriting Individu", "8711", "FICKI"));
		result.add(new DropDown("Underwriting Individu", "8711", "CHIZNI"));
		result.add(new DropDown("Underwriting Individu", "8711", "SUPRIYATI"));
		result.add(new DropDown("Underwriting Individu", "8898", "ABU JAMAL"));
		result.add(new DropDown("Underwriting Individu", "8898", "HADI"));
		
		return result;
	}
	
}
