package com.ekalife.webservice.klien;

import javax.xml.ws.WebFault;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "CreateAccountFault", targetNamespace = "http://agency.banksinarmas.com/customer")
public class CreateAccountFault_Exception extends Exception {

	/**
	 * Java type that goes as soapenv:Fault detail element.
	 * 
	 */
	private CreateAccountFault faultInfo;

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 */
	public CreateAccountFault_Exception(String message,
			CreateAccountFault faultInfo) {
		super(message);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 * @param cause
	 */
	public CreateAccountFault_Exception(String message,
			CreateAccountFault faultInfo, Throwable cause) {
		super(message, cause);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @return returns fault bean:
	 *         com.ekalife.webservice.klien.CreateAccountFault
	 */
	public CreateAccountFault getFaultInfo() {
		return faultInfo;
	}

}
