package com.ekalife.webservice.klien;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * CustomerAgencyService service = new CustomerAgencyService();
 * CustomerAgencyPortType portType = service.getCustomerAgencyPort();
 * portType.createAccount(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "CustomerAgencyService", targetNamespace = "http://agency.banksinarmas.com/customer", wsdlLocation = "http://10.39.7.8:8080/channelingAgency-UAT/customer?wsdl")
public class CustomerAgencyService extends Service {
	
	protected static final Log logger = LogFactory.getLog( CustomerAgencyService.class );

	private final static URL CUSTOMERAGENCYSERVICE_WSDL_LOCATION;
//	private final static Logger logger = Logger
//			.getLogger(com.ekalife.webservice.klien.CustomerAgencyService.class
//					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.ekalife.webservice.klien.CustomerAgencyService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://10.39.7.8:8080/channelingAgency-UAT/customer?wsdl");
		} catch (MalformedURLException e) {
			logger.error("Failed to create URL for the wsdl Location: 'http://10.39.7.8:8080/channelingAgency-UAT/customer?wsdl', retrying as a local file");
			logger.error("ERROR :", e);
		}
		CUSTOMERAGENCYSERVICE_WSDL_LOCATION = url;
	}

	public CustomerAgencyService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public CustomerAgencyService() {
		super(CUSTOMERAGENCYSERVICE_WSDL_LOCATION, new QName(
				"http://agency.banksinarmas.com/customer",
				"CustomerAgencyService"));
	}

	/**
	 * 
	 * @return returns CustomerAgencyPortType
	 */
	@WebEndpoint(name = "CustomerAgencyPort")
	public CustomerAgencyPortType getCustomerAgencyPort() {
		return super.getPort(
				new QName("http://agency.banksinarmas.com/customer",
						"CustomerAgencyPort"), CustomerAgencyPortType.class);
	}

}
