package com.ekalife.webservice.klien;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "CustomerAgencyPortType", targetNamespace = "http://agency.banksinarmas.com/customer")
public interface CustomerAgencyPortType {

	/**
	 * 
	 * @param message
	 * @param responseCode
	 * @param parameter
	 * @param customer
	 * @param channel
	 * @throws CreateAccountFault_Exception
	 */
	@WebMethod(operationName = "CreateAccount")
	@RequestWrapper(localName = "CreateAccount", targetNamespace = "http://agency.banksinarmas.com/customer", className = "com.ekalife.webservice.klien.CreateAccount")
	@ResponseWrapper(localName = "CreateAccountResponse", targetNamespace = "http://agency.banksinarmas.com/customer", className = "com.ekalife.webservice.klien.CreateAccountResponse")
	public void createAccount(
			@WebParam(name = "channel", targetNamespace = "http://agency.banksinarmas.com/customer") ChannelDetail channel,
			@WebParam(name = "customer", targetNamespace = "http://agency.banksinarmas.com/customer") CustomerDetail customer,
			@WebParam(name = "responseCode", targetNamespace = "http://agency.banksinarmas.com/customer", mode = WebParam.Mode.OUT) Holder<String> responseCode,
			@WebParam(name = "message", targetNamespace = "http://agency.banksinarmas.com/customer", mode = WebParam.Mode.OUT) Holder<String> message,
			@WebParam(name = "parameter", targetNamespace = "http://agency.banksinarmas.com/customer", mode = WebParam.Mode.OUT) Holder<String> parameter)
			throws CreateAccountFault_Exception;

	/**
	 * 
	 * @param startDate
	 * @param company
	 * @param endDate
	 * @return returns
	 *         java.util.List<com.ekalife.webservice.klien.ApprovedAccount>
	 */
	@WebMethod(operationName = "EnquiryApprovedAccount")
	@WebResult(name = "approvedAccount", targetNamespace = "http://agency.banksinarmas.com/customer")
	@RequestWrapper(localName = "EnquiryApprovedAccount", targetNamespace = "http://agency.banksinarmas.com/customer", className = "com.ekalife.webservice.klien.EnquiryApprovedAccount")
	@ResponseWrapper(localName = "EnquiryApprovedAccountResponse", targetNamespace = "http://agency.banksinarmas.com/customer", className = "com.ekalife.webservice.klien.EnquiryApprovedAccountResponse")
	public List<ApprovedAccount> enquiryApprovedAccount(
			@WebParam(name = "company", targetNamespace = "http://agency.banksinarmas.com/customer") String company,
			@WebParam(name = "startDate", targetNamespace = "http://agency.banksinarmas.com/customer") String startDate,
			@WebParam(name = "endDate", targetNamespace = "http://agency.banksinarmas.com/customer") String endDate);

	/**
	 * 
	 * @param startDate
	 * @param company
	 * @param endDate
	 * @return returns
	 *         java.util.List<com.ekalife.webservice.klien.RejectedAccount>
	 */
	@WebMethod(operationName = "EnquiryRejectedAccount")
	@WebResult(name = "rejectedAccount", targetNamespace = "http://agency.banksinarmas.com/customer")
	@RequestWrapper(localName = "EnquiryRejectedAccount", targetNamespace = "http://agency.banksinarmas.com/customer", className = "com.ekalife.webservice.klien.EnquiryRejectedAccount")
	@ResponseWrapper(localName = "EnquiryRejectedAccountResponse", targetNamespace = "http://agency.banksinarmas.com/customer", className = "com.ekalife.webservice.klien.EnquiryRejectedAccountResponse")
	public List<RejectedAccount> enquiryRejectedAccount(
			@WebParam(name = "company", targetNamespace = "http://agency.banksinarmas.com/customer") String company,
			@WebParam(name = "startDate", targetNamespace = "http://agency.banksinarmas.com/customer") String startDate,
			@WebParam(name = "endDate", targetNamespace = "http://agency.banksinarmas.com/customer") String endDate);

	/**
	 * 
	 * @param custcode
	 * @param company
	 * @return returns
	 *         java.util.List<com.ekalife.webservice.klien.AccountbyCustcode>
	 */
	@WebMethod(operationName = "EnquiryAccountbyCustcode")
	@WebResult(name = "accountbyCustcode", targetNamespace = "http://agency.banksinarmas.com/customer")
	@RequestWrapper(localName = "EnquiryAccountbyCustcode", targetNamespace = "http://agency.banksinarmas.com/customer", className = "com.ekalife.webservice.klien.EnquiryAccountbyCustcode")
	@ResponseWrapper(localName = "EnquiryAccountbyCustcodeResponse", targetNamespace = "http://agency.banksinarmas.com/customer", className = "com.ekalife.webservice.klien.EnquiryAccountbyCustcodeResponse")
	public List<AccountbyCustcode> enquiryAccountbyCustcode(
			@WebParam(name = "company", targetNamespace = "http://agency.banksinarmas.com/customer") String company,
			@WebParam(name = "custcode", targetNamespace = "http://agency.banksinarmas.com/customer") String custcode);

}
